In [45]:
#importing NumPy and Pandas
import numpy as np
import pandas as pd

In [46]:
#Ans: 1---- Generating array of zeroes using inbuilt numpy function
zero_array = np.zeros((4,3))
print("Zeros arry of 4 x 3\n")
print(zero_array)

Zeros arry of 4 x 3

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
#Ans: 2 ---- Finding the dot product of two arrays

a = np.random.randint(2, 10, (3, 4))
print("First Matrix:- \n")
print(a)

b = np.random.randint(2, 10, (4,3))
print("\nSecond Matrix:- \n")
print(b)

#finding dot product of two arrays
result=np.dot(a,b)

print("\nThe resultant array is:- \n")
print(result)


First Matrix:- 

[[7 2 8 5]
 [6 3 8 4]
 [3 4 2 2]]

Second Matrix:- 

[[2 8 4]
 [4 8 8]
 [5 9 9]
 [6 9 4]]

The resultant array is:- 

[[ 92 189 136]
 [ 88 180 136]
 [ 44  92  70]]


In [62]:
#Ans: 3 --- Reading CSV file using panda and displaying the first 5 entries

data = pd.read_csv("/content/drive/MyDrive/ASP.Net Tranining Videos/DataSet/data.csv")

#Displaying first 5 entries of the CSV File

#print(data.head()) #Default its value is 5
#first_five_entries=data.head(5)
#print(first_five_entries.to_string())

data.head(5)

OBJECTID                        UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
0        21        Fort Stevenson State Park  ...   0.000284   0.135641
1        22           Beaver Lake State Park  ...   0.000129   0.080067
2        23  Fort Abraham Lincoln State Park  ...   0.000399   0.119868
3        24           Fort Ransom State Park  ...   0.000444   0.128733
4        25        Grahams Island State Park  ...   0.000469   0.125546

[5 rows x 6 columns]

In [49]:
#Ans: 4 --- Describing data with all features
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   OBJECTID     25 non-null     int64  
 1   UNIT_NAME    25 non-null     object 
 2   DESCRIPTION  25 non-null     object 
 3   ACRES        25 non-null     float64
 4   SHAPE.AREA   25 non-null     float64
 5   SHAPE.LEN    25 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 1.3+ KB
None


In [50]:
print(data.describe())

        OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
count  25.000000    25.000000   25.000000  25.000000
mean   33.000000   724.134400    0.000352   0.109863
std     7.359801  1275.490247    0.000617   0.089073
min    21.000000    11.400000    0.000005   0.009396
25%    27.000000    72.300000    0.000034   0.033885
50%    33.000000   524.810000    0.000256   0.087192
75%    39.000000   836.470000    0.000399   0.145220
max    45.000000  6492.930000    0.003136   0.338800


In [63]:
#Ans: 5 ---- Finding the total count of missing values for each features
print(data.isnull().sum())
#print(data[pd.isnull(data)])

OBJECTID       0
UNIT_NAME      0
DESCRIPTION    0
ACRES          0
SHAPE.AREA     0
SHAPE.LEN      0
dtype: int64


In [53]:
#Ans: 6 ---- Displaying all the unique values from the "Description" column
print("Unique values of column DESCRIPTION\n")
print(data.DESCRIPTION.unique())
#print(data.DESCRIPTION.value_counts())

Unique values of column DESCRIPTION

['State Park' 'Interpretive Center' 'State Recreation Area'
 'State Natural Area' 'State Nature Preserve']


In [54]:
#Ans: 7 ----Creating a grouped table using "Description" as the grouping columns with the means of all other columns
print(data.groupby("DESCRIPTION").mean())

                        OBJECTID        ACRES  SHAPE.AREA  SHAPE.LEN
DESCRIPTION                                                         
Interpretive Center    29.000000    14.710000    0.000007   0.016774
State Natural Area     39.000000   219.615000    0.000105   0.077137
State Nature Preserve  39.500000    84.095000    0.000041   0.037175
State Park             28.538462  1168.668462    0.000567   0.150326
State Recreation Area  38.285714   326.934286    0.000162   0.078135


In [65]:
#Ans 8: ---- Generating a random sample of 10 rows from the data table
i = np.random.randint(0,(len(data)-10))
data.iloc[i:i+10,:]

OBJECTID                                   UNIT_NAME  ... SHAPE.AREA  SHAPE.LEN
13        36       Crow Flies High State Recreation Area  ...   0.000120   0.050518
14        33                     Turtle River State Park  ...   0.000378   0.145220
15        34                   Lake Sakakawea State Park  ...   0.000357   0.191806
16        37                  Elkhorn State Natural Area  ...   0.000127   0.067082
17        38         Fahlgren Park State Recreation Area  ...   0.000010   0.013294
18        39             Gunlogson State Nature Preserve  ...   0.000048   0.040465
19        40  Head of the Mountain State Nature Preserve  ...   0.000034   0.033885
20        41           Missouri River State Natural Area  ...   0.000083   0.087192
21        43         Pembina Gorge State Recreation Area  ...   0.000615   0.338800
22        44       Turtle Mountain State Recreation Area  ...   0.000345   0.086487

[10 rows x 6 columns]

In [72]:
#Ans: 9 ---- Adding a Featured called "New_feature" to the new DatSet and adding random float values in between 0 and 1 using Numpy
values= np.random.rand(25,1) #25 Means total number of rows and 1 Columns for New column New_Feature

data['New_feature']=values
data

OBJECTID  ... New_feature
0         21  ...    0.609340
1         22  ...    0.090961
2         23  ...    0.452419
3         24  ...    0.785865
4         25  ...    0.146559
5         26  ...    0.197108
6         27  ...    0.887900
7         28  ...    0.012682
8         29  ...    0.184010
9         30  ...    0.044400
10        31  ...    0.428998
11        32  ...    0.518367
12        35  ...    0.841004
13        36  ...    0.317236
14        33  ...    0.745947
15        34  ...    0.626397
16        37  ...    0.252304
17        38  ...    0.983728
18        39  ...    0.094598
19        40  ...    0.492926
20        41  ...    0.585650
21        43  ...    0.132454
22        44  ...    0.700837
23        45  ...    0.163593
24        42  ...    0.706827

[25 rows x 7 columns]

In [73]:
#Ans: 10 ---- Replacing zero value of column "ObjectID" with mean value permanently
mean_value = data['OBJECTID'].mean()
data.OBJECTID.replace(0,mean_value)
data

OBJECTID  ... New_feature
0         21  ...    0.609340
1         22  ...    0.090961
2         23  ...    0.452419
3         24  ...    0.785865
4         25  ...    0.146559
5         26  ...    0.197108
6         27  ...    0.887900
7         28  ...    0.012682
8         29  ...    0.184010
9         30  ...    0.044400
10        31  ...    0.428998
11        32  ...    0.518367
12        35  ...    0.841004
13        36  ...    0.317236
14        33  ...    0.745947
15        34  ...    0.626397
16        37  ...    0.252304
17        38  ...    0.983728
18        39  ...    0.094598
19        40  ...    0.492926
20        41  ...    0.585650
21        43  ...    0.132454
22        44  ...    0.700837
23        45  ...    0.163593
24        42  ...    0.706827

[25 rows x 7 columns]